INSERT INTO album (tituloAlbum,fecha,portada,stream)
VALUES
("Adrenaline", "1995-10-03", "/images/adrenaline.jpg", 427683779),
("Around the Fur", "1997-10-24", "/images/around-the-fur.jpg", 1596506595),
("White Pony", "2000-06-20", "/images/white-pony.jpg", 1358797291),
("Deftones", "2003-05-20", "/images/deftones-selftitled.jpg", 284390086),
("Saturday Night Wrist", "2006-10-31", "/images/saturday-night-wrist.jpg", 876168959),
("Diamond Eyes", "2010-04-23", "/images/diamond-eyes.jpg", 1015401451),
("Koi No Yokan", "2012-11-12", "/images/koi-no-yokan.jpg", 699266155),
("Gore", "2016-04-08", "/images/gore.jpg", 183209287),
("Ohms", "2020-09-25", "/images/ohms.jpg", 198625638),
("private music", "2025-08-22", "/images/private-music.jpg", 135334827);

INSERT INTO cancion (tituloCancion, glosa, idAlbum) VALUES
("Bored", NULL, 1),
("Minus Blindfold", NULL, 1),
("One Weak", NULL, 1),
("Nosebleed", NULL, 1),
("Lifter", NULL, 1),
("Root", "Los primeros 10 segundos fueron grabados en mono, sonando unicamente el parlante izquierdo. Imperceptible con los dispositivos usados en la actualidad.", 1),
("7 Words", "Chino la escribió con 16 años. Por que solo alguien de 16 años puede sentir tanto odio.", 1),
("Birthmark", NULL, 1),
("Engine No. 9", NULL, 1),
("Fireal", NULL, 1),
("Fist", NULL, 1),

("My Own Summer (Shove It)", "La parte de 'See I try to look up to the sky but my eyes burn' fue inspirada en la experiencia de Chino de grabar de noche y no poder dormir de día en el estudio. Papel de aluminio en las ventanas fue la solución.", 2),
("Lhabia", NULL, 2),
("Mascara", NULL, 2),
("Around the Fur", NULL, 2),
("Rickets", NULL, 2),
("Be Quiet and Drive (Far Away)", NULL, 2),
("Lotion", NULL, 2),
("Dai the Flu", NULL, 2),
("Headup", NULL, 2),
("MX", "La voz femenina es de Annalynn Cunningham, esposa en-su-momento de Abe. Los 37 minutos de pista no están de onda (o sí), esconden ''Bong Hit''(picardía llamarlo pista) y Damone.", 2),

("Feiticeira", NULL, 3),
("Digital Bath", NULL, 3),
("Elite", NULL, 3),
("Rx Queen", NULL, 3),
("Street Carp", NULL, 3),
("Teenager", NULL, 3),
("Knife Prty", NULL, 3),
("Korea", NULL, 3),
("Passenger", "Maynard de Tool participa de vocalista, pero su aporte fue mayor en la estructura de la canción en un momento que él describió que 'los chicos estaban pasando por un bloqueo creativo [...] Les hice cambiar de instrumento, tocar los cuencos [..] Era como si yo llevara collares de hippie y orejas de conejo. Podía sentir a Stephen pensando: '¿Qué clase de mierda psicodélica es esta?' '.", 3),
("Change (In the House of Flies)", NULL, 3),
("Pink Maggit", NULL, 3),

("Hexagram", NULL, 4),
("Needles and Pins", NULL, 4),
("Minerva", NULL, 4),
("Good Morning Beautiful", NULL, 4),
("Deathblow", NULL, 4),
("When Girls Telephone Boys", NULL, 4),
("Battle-Axe", NULL, 4),
("Lucky You", NULL, 4),
("Bloody Cape", NULL, 4),
("Anniversary of an Uninteresting Event", NULL, 4),
("Moana", NULL, 4),

("Hole in the Earth", "Según Chino en una entrevista en Argentina 2007, el nombre del album no tiene mas significado que 'la sensacion de dormirte borracho sobre tu propio brazo y despertarte sin poder moverlo'.", 5),
("Rapture", NULL, 5),
("Beware", NULL, 5),
("Cherry Waves", NULL, 5),
("Mein", "Serj Tankian de System of a Down hace coros en esta canción.", 5),
("U,U,D,D,L,R,L,R,A,B,Select,Start", "El titulo es conocido como el 'Konami Code'. Desbloquea easter eggs en miles de videojuegos, como Silent Hill 3 y Dead by Daylight.", 5),
("Xerces", NULL, 5),
("Rats!Rats!Rats!", NULL, 5),
("Pink Cellphone", NULL, 5),
("Combat", NULL, 5),
("Kimdracula", NULL, 5),
("Riviere", NULL, 5),
("Drive", NULL, 5),

("Diamond Eyes", "Chino recientemente confirmó el rumor de que el álbum les costó una multa de USD1.000.000 impuesta por la disquera, porque no cumplieron con el plazo de tiempo de finalización pactado.", 6),
("Royal", NULL, 6),
("CMND/CTRL", NULL, 6),
("You've Seen the Butcher", NULL, 6),
("Beauty School", NULL, 6),
("Prince", NULL, 6),
("Rocket Skates", NULL, 6),
("Sextape", "Chino comenta haber escrito la letra en base al sentimiento que le provocaba las tres notas principales de la canción, sin una historia muy marcada.", 6),
("Risk", NULL, 6),
("976-EVIL", NULL, 6),
("This Place Is Death", NULL, 6),

("Swerve City", "El nombre del album proviene del japonés y referencia 'la sensación al conocer a alguien de quien inevitablemente te enamorarás'.", 7),
("Romantic Dreams", NULL, 7),
("Leathers", NULL, 7),
("Poltergeist", NULL, 7),
("Entombed", NULL, 7),
("Graphic Nature", NULL, 7),
("Tempest", NULL, 7),
("Gauze", NULL, 7),
("Rosemary", NULL, 7),
("Goon Squad", NULL, 7),
("What Happened to You?", NULL, 7),

("Prayers / Triangles", NULL, 8),
("Acid Hologram", NULL, 8),
("Doomed User", NULL, 8),
("Geometric Headdress", NULL, 8),
("Hearts / Wires", NULL, 8),
("Pittura Infamante", NULL, 8),
("Xenon", NULL, 8),
("(L)MIRL", NULL, 8),
("Gore", NULL, 8),
("Phantom Bride", NULL, 8),
("Rubicon", NULL, 8),

("Genesis", NULL, 9),
("Ceremony", NULL, 9),
("Urantia", NULL, 9),
("Error", NULL, 9),
("The Spell of Mathematics", NULL, 9),
("Pompeji", NULL, 9),
("This Link Is Dead", "Inspiración de esta pagina, servidora!!!¡", 9),
("Radiant City", NULL, 9),
("Headless", NULL, 9),
("Ohms", NULL, 9),

("my mind is a mountain", "Normaliza experimentar euforia extrema y, a veces, tristeza extrema", 10),
("locked club", NULL, 10),
("ecdysis", NULL, 10),
("infinite source", NULL, 10),
("souvenir", NULL, 10),
("cXz", NULL, 10),
("i think about you all the time", NULL, 10),
("milk of the madonna", NULL, 10),
("cut hands", NULL, 10),
("~metal dream", NULL, 10),
("departing the body", NULL, 10);